name = "rose-nail-pub"
compatibility_date = "2024-03-11"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."
dist = "out"

[site]
bucket = "out"
entry-point = "."

# Production environment only
[env.production]
name = "rose-nail-pub"

# Add the pages build output directory
pages_build_output_dir = "out" 