name = "rose-nail-pub"
compatibility_date = "2024-03-12"

# Build configuration
[build]
command = "npm run build"
output_directory = "out"

# Environment-specific configurations
[env.production]
name = "rose-nail-pub"

# Pages configuration
pages_build_output_dir = "out" 